package model.person;

public enum Categoria {
	ADMIN_MASTER,
	ADMIN,
	MONITOR,
	MONITORADO,
	ADMIN_MONITOR,
	ADMIN_MONITORADO,
	ADMIN_MONITOR_MONITORADO,
	MONITOR_MONITORADO,
	ADMIN_MASTER_MONITOR,
	ADMIN_MASTER_MONITORADO,
	ADMIN_MASTER_MONITOR_MONITORADO;
}
